-- MySQL Script generated by MySQL Workbench
-- Sat May 28 19:21:59 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema PFR
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema PFR
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PFR` DEFAULT CHARACTER SET utf8 ;
USE `PFR` ;

-- -----------------------------------------------------
-- Table `PFR`.`categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PFR`.`categorie` (
  `idcategorie` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  PRIMARY KEY (`idcategorie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PFR`.`utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PFR`.`utilisateur` (
  `idutilisateur` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `passWord` VARCHAR(45) NULL,
  PRIMARY KEY (`idutilisateur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PFR`.`Recettes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PFR`.`Recettes` (
  `idRecettes` INT NOT NULL,
  `Nom` VARCHAR(45) NULL,
  `duree` VARCHAR(45) NULL,
  `description` VARCHAR(255) BINARY NULL,
  `idcategorie` INT NOT NULL,
  `idutilisateur` INT NOT NULL,
  PRIMARY KEY (`idRecettes`, `idcategorie`, `idutilisateur`),
  CONSTRAINT `fk_Recettes_categorie1`
    FOREIGN KEY (`idcategorie`)
    REFERENCES `PFR`.`categorie` (`idcategorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Recettes_utilisateur1`
    FOREIGN KEY (`idutilisateur`)
    REFERENCES `PFR`.`utilisateur` (`idutilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Recettes_categorie1_idx` ON `PFR`.`Recettes` (`idcategorie` ASC) VISIBLE;

CREATE INDEX `fk_Recettes_utilisateur1_idx` ON `PFR`.`Recettes` (`idutilisateur` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `PFR`.`ingredient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PFR`.`ingredient` (
  `idIngredient` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `ingredientcol` VARCHAR(45) NULL,
  PRIMARY KEY (`idIngredient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PFR`.`ingredient_has_Recettes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PFR`.`ingredient_has_Recettes` (
  `ingredient_idIngredient` INT NOT NULL,
  `Recettes_idRecettes` INT NOT NULL,
  PRIMARY KEY (`ingredient_idIngredient`, `Recettes_idRecettes`),
  CONSTRAINT `fk_ingredient_has_Recettes_ingredient1`
    FOREIGN KEY (`ingredient_idIngredient`)
    REFERENCES `PFR`.`ingredient` (`idIngredient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ingredient_has_Recettes_Recettes1`
    FOREIGN KEY (`Recettes_idRecettes`)
    REFERENCES `PFR`.`Recettes` (`idRecettes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ingredient_has_Recettes_Recettes1_idx` ON `PFR`.`ingredient_has_Recettes` (`Recettes_idRecettes` ASC) VISIBLE;

CREATE INDEX `fk_ingredient_has_Recettes_ingredient1_idx` ON `PFR`.`ingredient_has_Recettes` (`ingredient_idIngredient` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
