-- MySQL Script generated by MySQL Workbench
-- Fri Jun 10 00:19:46 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema PFR
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema PFR
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PFR` DEFAULT CHARACTER SET utf8 ;
USE `PFR` ;

-- -----------------------------------------------------
-- Table `PFR`.`utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PFR`.`utilisateur` (
  `idutilisateur` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `passWord` VARCHAR(45) NULL,
  PRIMARY KEY (`idutilisateur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PFR`.`recettes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PFR`.`recettes` (
  `idRecettes` INT NOT NULL,
  `Nom` VARCHAR(45) NULL,
  `duree` VARCHAR(45) NULL,
  `description` VARCHAR(255) BINARY NULL,
  `idutilisateur` INT NOT NULL,
  PRIMARY KEY (`idRecettes`, `idutilisateur`),
  INDEX `fk_Recettes_utilisateur1_idx` (`idutilisateur` ASC) VISIBLE,
  CONSTRAINT `fk_Recettes_utilisateur1`
    FOREIGN KEY (`idutilisateur`)
    REFERENCES `PFR`.`utilisateur` (`idutilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PFR`.`categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PFR`.`categorie` (
  `idcategorie` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  PRIMARY KEY (`idcategorie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PFR`.`ingredients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PFR`.`ingredients` (
  `idIngredient` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `ingredientcol` VARCHAR(45) NULL,
  `categorie_idcategorie` INT NOT NULL,
  `photo` VARCHAR(45) NULL,
  PRIMARY KEY (`idIngredient`, `categorie_idcategorie`),
  INDEX `fk_ingredient_categorie1_idx` (`categorie_idcategorie` ASC) VISIBLE,
  CONSTRAINT `fk_ingredient_categorie1`
    FOREIGN KEY (`categorie_idcategorie`)
    REFERENCES `PFR`.`categorie` (`idcategorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PFR`.`ingredients_recettes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PFR`.`ingredients_recettes` (
  `id_ingredient` INT NOT NULL COMMENT 'id_ingredient',
  `id_recette` INT NOT NULL,
  PRIMARY KEY (`id_ingredient`, `id_recette`),
  INDEX `fk_ingredient_has_Recettes_Recettes1_idx` (`id_recette` ASC) VISIBLE,
  INDEX `fk_ingredient_has_Recettes_ingredient1_idx` (`id_ingredient` ASC) VISIBLE,
  CONSTRAINT `fk_ingredient_has_Recettes_ingredient1`
    FOREIGN KEY (`id_ingredient`)
    REFERENCES `PFR`.`ingredients` (`idIngredient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ingredient_has_Recettes_Recettes1`
    FOREIGN KEY (`id_recette`)
    REFERENCES `PFR`.`recettes` (`idRecettes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
